### ISSUE TITLE
certificate-creds.json needed to build

### ISSUE THREAD

**Issue by EricKramp** [WestonThayer/Bloks#1]
Hey @WestonThayer,

I'm excited to try out your Illustrator plugin, but I'm having some troubles with the build process. Specifically I'm getting hung up on running the NPM build command.  There were a bunch of missing gulp dependencies, which I think are all resolved, but now I seem to be missing some kind of credentials.

```
gulp build-jsx

/Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/gulpfile.js:65
        throw new Error("./zxp-tools/certificate-creds.json doesn't exist! Please create it. Ex: { password: 'pwd' }");
        ^

Error: ./zxp-tools/certificate-creds.json doesn't exist! Please create it. Ex: { password: 'pwd' }
    at Object.<anonymous> (/Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/gulpfile.js:65:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-jsx"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! com.westonthayer.bloks@1.0.0 build-jsx: `gulp build-jsx`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the com.westonthayer.bloks@1.0.0 build-jsx script 'gulp build-jsx'.
npm ERR! This is most likely a problem with the com.westonthayer.bloks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build-jsx
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs com.westonthayer.bloks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls com.westonthayer.bloks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eric/Library/Application Support/Adobe/CEP/extensions/com.westonthayer.bloks/npm-debug.log
```

If you know the best way to resolve this one I'd appreciate it. Thanks!

**Comment by WestonThayer** [comment]
Ah, thanks. I forgot to put in a check for that file not existing. Should be fixed now, just pull the latest version.

Also, the plugin currently won't boot with the latest version of Illustrator (released last week, CC 2015.3 or v17.0). Haven't had time to work out a fix yet.

Anyway, I'll have time in a few days. I'll also have a better way to install for people who aren't looking to contribute.

**Comment by EricKramp** [comment]
Cool, thanks for the quick response!

I pulled, and now I'm getting another error

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeScript error: node_modules/tsify/node_modules/tsconfig/dist/tsconfig.d.ts(1,26): Error TS2307: Cannot find module 'pinkie-promise'.
```

Seems like a missing module, which previously I've been able to resolve by running "npm install {module name}". Unfortunately that doesn't seem to resolve this one.

If you have an easier install process coming I'm happy to wait a few days for that, but I'm also happy to help try out fixes for this if that's useful.

**Comment by WestonThayer** [comment]
Hmmm that looks like an issue with the tsify npm package. I haven't run npm install in a long while. It's possible they fixed it, you could try `npm outdated` to see if there's an upgrade available.

I'll take a look as soon as I can.

**Comment by EricKramp** [comment]
That would be great, I'm definitely up to date with npm so unfortunately no luck there.

**Comment by EricKramp** [comment]
@WestonThayer, I got it to work by running `npm install` again after pulling your update, so my guess is that someone pulling fresh probably won't have any issues.
